// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/VladPetriv/scanner_backend/internal/model"

// ReplieRepo is an autogenerated mock type for the ReplieRepo type
type ReplieRepo struct {
	mock.Mock
}

// GetFullRepliesByMessageID provides a mock function with given fields: ID
func (_m *ReplieRepo) GetFullRepliesByMessageID(ID int) ([]model.FullReplie, error) {
	ret := _m.Called(ID)

	var r0 []model.FullReplie
	if rf, ok := ret.Get(0).(func(int) []model.FullReplie); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FullReplie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplie provides a mock function with given fields: replieID
func (_m *ReplieRepo) GetReplie(replieID int) (*model.Replie, error) {
	ret := _m.Called(replieID)

	var r0 *model.Replie
	if rf, ok := ret.Get(0).(func(int) *model.Replie); ok {
		r0 = rf(replieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Replie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(replieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplieByName provides a mock function with given fields: name
func (_m *ReplieRepo) GetReplieByName(name string) (*model.Replie, error) {
	ret := _m.Called(name)

	var r0 *model.Replie
	if rf, ok := ret.Get(0).(func(string) *model.Replie); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Replie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplies provides a mock function with given fields:
func (_m *ReplieRepo) GetReplies() ([]model.Replie, error) {
	ret := _m.Called()

	var r0 []model.Replie
	if rf, ok := ret.Get(0).(func() []model.Replie); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Replie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
