// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/VladPetriv/scanner_backend/internal/model"

// SavedService is an autogenerated mock type for the SavedService type
type SavedService struct {
	mock.Mock
}

// CreateSavedMessage provides a mock function with given fields: saved
func (_m *SavedService) CreateSavedMessage(saved *model.Saved) error {
	ret := _m.Called(saved)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Saved) error); ok {
		r0 = rf(saved)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSavedMessage provides a mock function with given fields: ID
func (_m *SavedService) DeleteSavedMessage(ID int) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSavedMessageByMessageID provides a mock function with given fields: ID
func (_m *SavedService) GetSavedMessageByMessageID(ID int) (*model.Saved, error) {
	ret := _m.Called(ID)

	var r0 *model.Saved
	if rf, ok := ret.Get(0).(func(int) *model.Saved); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Saved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedMessages provides a mock function with given fields: UserID
func (_m *SavedService) GetSavedMessages(UserID int) ([]model.Saved, error) {
	ret := _m.Called(UserID)

	var r0 []model.Saved
	if rf, ok := ret.Get(0).(func(int) []model.Saved); ok {
		r0 = rf(UserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Saved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(UserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
